// edge_ipc.proto — 端侧 IPC 契约（UI ↔ edge-daemon）
//
// 对应 doc/3 §3 IPC 契约、doc/2 §5.2
// 传输层：gRPC / connect-go（同时支持 gRPC 与 gRPC-web）
// 版本：v1

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: edge_ipc.proto

package edgepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EdgeDaemonService_GetDeviceInfo_FullMethodName       = "/fancyprint.edge.v1.EdgeDaemonService/GetDeviceInfo"
	EdgeDaemonService_WatchDeviceStatus_FullMethodName   = "/fancyprint.edge.v1.EdgeDaemonService/WatchDeviceStatus"
	EdgeDaemonService_CreatePrintJob_FullMethodName      = "/fancyprint.edge.v1.EdgeDaemonService/CreatePrintJob"
	EdgeDaemonService_GetPrintJob_FullMethodName         = "/fancyprint.edge.v1.EdgeDaemonService/GetPrintJob"
	EdgeDaemonService_ListPrintJobs_FullMethodName       = "/fancyprint.edge.v1.EdgeDaemonService/ListPrintJobs"
	EdgeDaemonService_ConfirmPrint_FullMethodName        = "/fancyprint.edge.v1.EdgeDaemonService/ConfirmPrint"
	EdgeDaemonService_CancelPrintJob_FullMethodName      = "/fancyprint.edge.v1.EdgeDaemonService/CancelPrintJob"
	EdgeDaemonService_WatchPrintJobs_FullMethodName      = "/fancyprint.edge.v1.EdgeDaemonService/WatchPrintJobs"
	EdgeDaemonService_StartRecording_FullMethodName      = "/fancyprint.edge.v1.EdgeDaemonService/StartRecording"
	EdgeDaemonService_StopRecording_FullMethodName       = "/fancyprint.edge.v1.EdgeDaemonService/StopRecording"
	EdgeDaemonService_PlayAudio_FullMethodName           = "/fancyprint.edge.v1.EdgeDaemonService/PlayAudio"
	EdgeDaemonService_StopPlayback_FullMethodName        = "/fancyprint.edge.v1.EdgeDaemonService/StopPlayback"
	EdgeDaemonService_GetPreview_FullMethodName          = "/fancyprint.edge.v1.EdgeDaemonService/GetPreview"
	EdgeDaemonService_WatchPreview_FullMethodName        = "/fancyprint.edge.v1.EdgeDaemonService/WatchPreview"
	EdgeDaemonService_GetParentLockStatus_FullMethodName = "/fancyprint.edge.v1.EdgeDaemonService/GetParentLockStatus"
	EdgeDaemonService_ValidatePin_FullMethodName         = "/fancyprint.edge.v1.EdgeDaemonService/ValidatePin"
	EdgeDaemonService_SetPin_FullMethodName              = "/fancyprint.edge.v1.EdgeDaemonService/SetPin"
	EdgeDaemonService_UnlockDevice_FullMethodName        = "/fancyprint.edge.v1.EdgeDaemonService/UnlockDevice"
	EdgeDaemonService_GetSettings_FullMethodName         = "/fancyprint.edge.v1.EdgeDaemonService/GetSettings"
	EdgeDaemonService_UpdateSetting_FullMethodName       = "/fancyprint.edge.v1.EdgeDaemonService/UpdateSetting"
	EdgeDaemonService_FactoryReset_FullMethodName        = "/fancyprint.edge.v1.EdgeDaemonService/FactoryReset"
	EdgeDaemonService_ListWiFiNetworks_FullMethodName    = "/fancyprint.edge.v1.EdgeDaemonService/ListWiFiNetworks"
)

// EdgeDaemonServiceClient is the client API for EdgeDaemonService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EdgeDaemonServiceClient interface {
	// === 设备状态 ===
	GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*DeviceInfo, error)
	WatchDeviceStatus(ctx context.Context, in *WatchDeviceStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceStatus], error)
	// === 打印 ===
	CreatePrintJob(ctx context.Context, in *CreatePrintJobRequest, opts ...grpc.CallOption) (*PrintJob, error)
	GetPrintJob(ctx context.Context, in *GetPrintJobRequest, opts ...grpc.CallOption) (*PrintJob, error)
	ListPrintJobs(ctx context.Context, in *ListPrintJobsRequest, opts ...grpc.CallOption) (*ListPrintJobsResponse, error)
	ConfirmPrint(ctx context.Context, in *ConfirmPrintRequest, opts ...grpc.CallOption) (*PrintResult, error)
	CancelPrintJob(ctx context.Context, in *CancelPrintJobRequest, opts ...grpc.CallOption) (*CancelPrintJobResponse, error)
	WatchPrintJobs(ctx context.Context, in *WatchPrintJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrintJobEvent], error)
	// === 音频 ===
	StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*RecordingStatus, error)
	StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*RecordingResult, error)
	PlayAudio(ctx context.Context, in *PlayAudioRequest, opts ...grpc.CallOption) (*PlayAudioResponse, error)
	StopPlayback(ctx context.Context, in *StopPlaybackRequest, opts ...grpc.CallOption) (*StopPlaybackResponse, error)
	// === 预览（云端图片） ===
	GetPreview(ctx context.Context, in *GetPreviewRequest, opts ...grpc.CallOption) (*PreviewData, error)
	WatchPreview(ctx context.Context, in *WatchPreviewRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewNotification], error)
	// === 家长锁 ===
	GetParentLockStatus(ctx context.Context, in *GetParentLockStatusRequest, opts ...grpc.CallOption) (*ParentLockStatus, error)
	ValidatePin(ctx context.Context, in *ValidatePinRequest, opts ...grpc.CallOption) (*ValidatePinResponse, error)
	SetPin(ctx context.Context, in *SetPinRequest, opts ...grpc.CallOption) (*SetPinResponse, error)
	UnlockDevice(ctx context.Context, in *UnlockDeviceRequest, opts ...grpc.CallOption) (*UnlockDeviceResponse, error)
	// === 设置 ===
	GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*Settings, error)
	UpdateSetting(ctx context.Context, in *UpdateSettingRequest, opts ...grpc.CallOption) (*UpdateSettingResponse, error)
	FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*FactoryResetResponse, error)
	// === WiFi ===
	ListWiFiNetworks(ctx context.Context, in *ListWiFiNetworksRequest, opts ...grpc.CallOption) (*ListWiFiNetworksResponse, error)
}

type edgeDaemonServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEdgeDaemonServiceClient(cc grpc.ClientConnInterface) EdgeDaemonServiceClient {
	return &edgeDaemonServiceClient{cc}
}

func (c *edgeDaemonServiceClient) GetDeviceInfo(ctx context.Context, in *GetDeviceInfoRequest, opts ...grpc.CallOption) (*DeviceInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeviceInfo)
	err := c.cc.Invoke(ctx, EdgeDaemonService_GetDeviceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) WatchDeviceStatus(ctx context.Context, in *WatchDeviceStatusRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[DeviceStatus], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EdgeDaemonService_ServiceDesc.Streams[0], EdgeDaemonService_WatchDeviceStatus_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchDeviceStatusRequest, DeviceStatus]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeDaemonService_WatchDeviceStatusClient = grpc.ServerStreamingClient[DeviceStatus]

func (c *edgeDaemonServiceClient) CreatePrintJob(ctx context.Context, in *CreatePrintJobRequest, opts ...grpc.CallOption) (*PrintJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintJob)
	err := c.cc.Invoke(ctx, EdgeDaemonService_CreatePrintJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) GetPrintJob(ctx context.Context, in *GetPrintJobRequest, opts ...grpc.CallOption) (*PrintJob, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintJob)
	err := c.cc.Invoke(ctx, EdgeDaemonService_GetPrintJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) ListPrintJobs(ctx context.Context, in *ListPrintJobsRequest, opts ...grpc.CallOption) (*ListPrintJobsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPrintJobsResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_ListPrintJobs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) ConfirmPrint(ctx context.Context, in *ConfirmPrintRequest, opts ...grpc.CallOption) (*PrintResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrintResult)
	err := c.cc.Invoke(ctx, EdgeDaemonService_ConfirmPrint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) CancelPrintJob(ctx context.Context, in *CancelPrintJobRequest, opts ...grpc.CallOption) (*CancelPrintJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelPrintJobResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_CancelPrintJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) WatchPrintJobs(ctx context.Context, in *WatchPrintJobsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PrintJobEvent], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EdgeDaemonService_ServiceDesc.Streams[1], EdgeDaemonService_WatchPrintJobs_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPrintJobsRequest, PrintJobEvent]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeDaemonService_WatchPrintJobsClient = grpc.ServerStreamingClient[PrintJobEvent]

func (c *edgeDaemonServiceClient) StartRecording(ctx context.Context, in *StartRecordingRequest, opts ...grpc.CallOption) (*RecordingStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordingStatus)
	err := c.cc.Invoke(ctx, EdgeDaemonService_StartRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) StopRecording(ctx context.Context, in *StopRecordingRequest, opts ...grpc.CallOption) (*RecordingResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordingResult)
	err := c.cc.Invoke(ctx, EdgeDaemonService_StopRecording_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) PlayAudio(ctx context.Context, in *PlayAudioRequest, opts ...grpc.CallOption) (*PlayAudioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PlayAudioResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_PlayAudio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) StopPlayback(ctx context.Context, in *StopPlaybackRequest, opts ...grpc.CallOption) (*StopPlaybackResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopPlaybackResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_StopPlayback_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) GetPreview(ctx context.Context, in *GetPreviewRequest, opts ...grpc.CallOption) (*PreviewData, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewData)
	err := c.cc.Invoke(ctx, EdgeDaemonService_GetPreview_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) WatchPreview(ctx context.Context, in *WatchPreviewRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[PreviewNotification], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EdgeDaemonService_ServiceDesc.Streams[2], EdgeDaemonService_WatchPreview_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[WatchPreviewRequest, PreviewNotification]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeDaemonService_WatchPreviewClient = grpc.ServerStreamingClient[PreviewNotification]

func (c *edgeDaemonServiceClient) GetParentLockStatus(ctx context.Context, in *GetParentLockStatusRequest, opts ...grpc.CallOption) (*ParentLockStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParentLockStatus)
	err := c.cc.Invoke(ctx, EdgeDaemonService_GetParentLockStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) ValidatePin(ctx context.Context, in *ValidatePinRequest, opts ...grpc.CallOption) (*ValidatePinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidatePinResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_ValidatePin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) SetPin(ctx context.Context, in *SetPinRequest, opts ...grpc.CallOption) (*SetPinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPinResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_SetPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) UnlockDevice(ctx context.Context, in *UnlockDeviceRequest, opts ...grpc.CallOption) (*UnlockDeviceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockDeviceResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_UnlockDevice_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) GetSettings(ctx context.Context, in *GetSettingsRequest, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, EdgeDaemonService_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) UpdateSetting(ctx context.Context, in *UpdateSettingRequest, opts ...grpc.CallOption) (*UpdateSettingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSettingResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_UpdateSetting_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) FactoryReset(ctx context.Context, in *FactoryResetRequest, opts ...grpc.CallOption) (*FactoryResetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FactoryResetResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_FactoryReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *edgeDaemonServiceClient) ListWiFiNetworks(ctx context.Context, in *ListWiFiNetworksRequest, opts ...grpc.CallOption) (*ListWiFiNetworksResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWiFiNetworksResponse)
	err := c.cc.Invoke(ctx, EdgeDaemonService_ListWiFiNetworks_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EdgeDaemonServiceServer is the server API for EdgeDaemonService service.
// All implementations must embed UnimplementedEdgeDaemonServiceServer
// for forward compatibility.
type EdgeDaemonServiceServer interface {
	// === 设备状态 ===
	GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*DeviceInfo, error)
	WatchDeviceStatus(*WatchDeviceStatusRequest, grpc.ServerStreamingServer[DeviceStatus]) error
	// === 打印 ===
	CreatePrintJob(context.Context, *CreatePrintJobRequest) (*PrintJob, error)
	GetPrintJob(context.Context, *GetPrintJobRequest) (*PrintJob, error)
	ListPrintJobs(context.Context, *ListPrintJobsRequest) (*ListPrintJobsResponse, error)
	ConfirmPrint(context.Context, *ConfirmPrintRequest) (*PrintResult, error)
	CancelPrintJob(context.Context, *CancelPrintJobRequest) (*CancelPrintJobResponse, error)
	WatchPrintJobs(*WatchPrintJobsRequest, grpc.ServerStreamingServer[PrintJobEvent]) error
	// === 音频 ===
	StartRecording(context.Context, *StartRecordingRequest) (*RecordingStatus, error)
	StopRecording(context.Context, *StopRecordingRequest) (*RecordingResult, error)
	PlayAudio(context.Context, *PlayAudioRequest) (*PlayAudioResponse, error)
	StopPlayback(context.Context, *StopPlaybackRequest) (*StopPlaybackResponse, error)
	// === 预览（云端图片） ===
	GetPreview(context.Context, *GetPreviewRequest) (*PreviewData, error)
	WatchPreview(*WatchPreviewRequest, grpc.ServerStreamingServer[PreviewNotification]) error
	// === 家长锁 ===
	GetParentLockStatus(context.Context, *GetParentLockStatusRequest) (*ParentLockStatus, error)
	ValidatePin(context.Context, *ValidatePinRequest) (*ValidatePinResponse, error)
	SetPin(context.Context, *SetPinRequest) (*SetPinResponse, error)
	UnlockDevice(context.Context, *UnlockDeviceRequest) (*UnlockDeviceResponse, error)
	// === 设置 ===
	GetSettings(context.Context, *GetSettingsRequest) (*Settings, error)
	UpdateSetting(context.Context, *UpdateSettingRequest) (*UpdateSettingResponse, error)
	FactoryReset(context.Context, *FactoryResetRequest) (*FactoryResetResponse, error)
	// === WiFi ===
	ListWiFiNetworks(context.Context, *ListWiFiNetworksRequest) (*ListWiFiNetworksResponse, error)
	mustEmbedUnimplementedEdgeDaemonServiceServer()
}

// UnimplementedEdgeDaemonServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEdgeDaemonServiceServer struct{}

func (UnimplementedEdgeDaemonServiceServer) GetDeviceInfo(context.Context, *GetDeviceInfoRequest) (*DeviceInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDeviceInfo not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) WatchDeviceStatus(*WatchDeviceStatusRequest, grpc.ServerStreamingServer[DeviceStatus]) error {
	return status.Error(codes.Unimplemented, "method WatchDeviceStatus not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) CreatePrintJob(context.Context, *CreatePrintJobRequest) (*PrintJob, error) {
	return nil, status.Error(codes.Unimplemented, "method CreatePrintJob not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) GetPrintJob(context.Context, *GetPrintJobRequest) (*PrintJob, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPrintJob not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) ListPrintJobs(context.Context, *ListPrintJobsRequest) (*ListPrintJobsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPrintJobs not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) ConfirmPrint(context.Context, *ConfirmPrintRequest) (*PrintResult, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfirmPrint not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) CancelPrintJob(context.Context, *CancelPrintJobRequest) (*CancelPrintJobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelPrintJob not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) WatchPrintJobs(*WatchPrintJobsRequest, grpc.ServerStreamingServer[PrintJobEvent]) error {
	return status.Error(codes.Unimplemented, "method WatchPrintJobs not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) StartRecording(context.Context, *StartRecordingRequest) (*RecordingStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method StartRecording not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) StopRecording(context.Context, *StopRecordingRequest) (*RecordingResult, error) {
	return nil, status.Error(codes.Unimplemented, "method StopRecording not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) PlayAudio(context.Context, *PlayAudioRequest) (*PlayAudioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PlayAudio not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) StopPlayback(context.Context, *StopPlaybackRequest) (*StopPlaybackResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopPlayback not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) GetPreview(context.Context, *GetPreviewRequest) (*PreviewData, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPreview not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) WatchPreview(*WatchPreviewRequest, grpc.ServerStreamingServer[PreviewNotification]) error {
	return status.Error(codes.Unimplemented, "method WatchPreview not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) GetParentLockStatus(context.Context, *GetParentLockStatusRequest) (*ParentLockStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method GetParentLockStatus not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) ValidatePin(context.Context, *ValidatePinRequest) (*ValidatePinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidatePin not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) SetPin(context.Context, *SetPinRequest) (*SetPinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPin not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) UnlockDevice(context.Context, *UnlockDeviceRequest) (*UnlockDeviceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UnlockDevice not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) GetSettings(context.Context, *GetSettingsRequest) (*Settings, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) UpdateSetting(context.Context, *UpdateSettingRequest) (*UpdateSettingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSetting not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) FactoryReset(context.Context, *FactoryResetRequest) (*FactoryResetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FactoryReset not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) ListWiFiNetworks(context.Context, *ListWiFiNetworksRequest) (*ListWiFiNetworksResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWiFiNetworks not implemented")
}
func (UnimplementedEdgeDaemonServiceServer) mustEmbedUnimplementedEdgeDaemonServiceServer() {}
func (UnimplementedEdgeDaemonServiceServer) testEmbeddedByValue()                           {}

// UnsafeEdgeDaemonServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EdgeDaemonServiceServer will
// result in compilation errors.
type UnsafeEdgeDaemonServiceServer interface {
	mustEmbedUnimplementedEdgeDaemonServiceServer()
}

func RegisterEdgeDaemonServiceServer(s grpc.ServiceRegistrar, srv EdgeDaemonServiceServer) {
	// If the following call panics, it indicates UnimplementedEdgeDaemonServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EdgeDaemonService_ServiceDesc, srv)
}

func _EdgeDaemonService_GetDeviceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).GetDeviceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_GetDeviceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).GetDeviceInfo(ctx, req.(*GetDeviceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_WatchDeviceStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchDeviceStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EdgeDaemonServiceServer).WatchDeviceStatus(m, &grpc.GenericServerStream[WatchDeviceStatusRequest, DeviceStatus]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeDaemonService_WatchDeviceStatusServer = grpc.ServerStreamingServer[DeviceStatus]

func _EdgeDaemonService_CreatePrintJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePrintJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).CreatePrintJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_CreatePrintJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).CreatePrintJob(ctx, req.(*CreatePrintJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_GetPrintJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPrintJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).GetPrintJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_GetPrintJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).GetPrintJob(ctx, req.(*GetPrintJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_ListPrintJobs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPrintJobsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).ListPrintJobs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_ListPrintJobs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).ListPrintJobs(ctx, req.(*ListPrintJobsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_ConfirmPrint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfirmPrintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).ConfirmPrint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_ConfirmPrint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).ConfirmPrint(ctx, req.(*ConfirmPrintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_CancelPrintJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelPrintJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).CancelPrintJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_CancelPrintJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).CancelPrintJob(ctx, req.(*CancelPrintJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_WatchPrintJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPrintJobsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EdgeDaemonServiceServer).WatchPrintJobs(m, &grpc.GenericServerStream[WatchPrintJobsRequest, PrintJobEvent]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeDaemonService_WatchPrintJobsServer = grpc.ServerStreamingServer[PrintJobEvent]

func _EdgeDaemonService_StartRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).StartRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_StartRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).StartRecording(ctx, req.(*StartRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_StopRecording_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRecordingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).StopRecording(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_StopRecording_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).StopRecording(ctx, req.(*StopRecordingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_PlayAudio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlayAudioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).PlayAudio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_PlayAudio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).PlayAudio(ctx, req.(*PlayAudioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_StopPlayback_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopPlaybackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).StopPlayback(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_StopPlayback_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).StopPlayback(ctx, req.(*StopPlaybackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_GetPreview_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPreviewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).GetPreview(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_GetPreview_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).GetPreview(ctx, req.(*GetPreviewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_WatchPreview_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WatchPreviewRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(EdgeDaemonServiceServer).WatchPreview(m, &grpc.GenericServerStream[WatchPreviewRequest, PreviewNotification]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EdgeDaemonService_WatchPreviewServer = grpc.ServerStreamingServer[PreviewNotification]

func _EdgeDaemonService_GetParentLockStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParentLockStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).GetParentLockStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_GetParentLockStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).GetParentLockStatus(ctx, req.(*GetParentLockStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_ValidatePin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidatePinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).ValidatePin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_ValidatePin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).ValidatePin(ctx, req.(*ValidatePinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_SetPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).SetPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_SetPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).SetPin(ctx, req.(*SetPinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_UnlockDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).UnlockDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_UnlockDevice_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).UnlockDevice(ctx, req.(*UnlockDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSettingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).GetSettings(ctx, req.(*GetSettingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_UpdateSetting_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSettingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).UpdateSetting(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_UpdateSetting_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).UpdateSetting(ctx, req.(*UpdateSettingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_FactoryReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FactoryResetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).FactoryReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_FactoryReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).FactoryReset(ctx, req.(*FactoryResetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EdgeDaemonService_ListWiFiNetworks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWiFiNetworksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EdgeDaemonServiceServer).ListWiFiNetworks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EdgeDaemonService_ListWiFiNetworks_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EdgeDaemonServiceServer).ListWiFiNetworks(ctx, req.(*ListWiFiNetworksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EdgeDaemonService_ServiceDesc is the grpc.ServiceDesc for EdgeDaemonService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EdgeDaemonService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fancyprint.edge.v1.EdgeDaemonService",
	HandlerType: (*EdgeDaemonServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetDeviceInfo",
			Handler:    _EdgeDaemonService_GetDeviceInfo_Handler,
		},
		{
			MethodName: "CreatePrintJob",
			Handler:    _EdgeDaemonService_CreatePrintJob_Handler,
		},
		{
			MethodName: "GetPrintJob",
			Handler:    _EdgeDaemonService_GetPrintJob_Handler,
		},
		{
			MethodName: "ListPrintJobs",
			Handler:    _EdgeDaemonService_ListPrintJobs_Handler,
		},
		{
			MethodName: "ConfirmPrint",
			Handler:    _EdgeDaemonService_ConfirmPrint_Handler,
		},
		{
			MethodName: "CancelPrintJob",
			Handler:    _EdgeDaemonService_CancelPrintJob_Handler,
		},
		{
			MethodName: "StartRecording",
			Handler:    _EdgeDaemonService_StartRecording_Handler,
		},
		{
			MethodName: "StopRecording",
			Handler:    _EdgeDaemonService_StopRecording_Handler,
		},
		{
			MethodName: "PlayAudio",
			Handler:    _EdgeDaemonService_PlayAudio_Handler,
		},
		{
			MethodName: "StopPlayback",
			Handler:    _EdgeDaemonService_StopPlayback_Handler,
		},
		{
			MethodName: "GetPreview",
			Handler:    _EdgeDaemonService_GetPreview_Handler,
		},
		{
			MethodName: "GetParentLockStatus",
			Handler:    _EdgeDaemonService_GetParentLockStatus_Handler,
		},
		{
			MethodName: "ValidatePin",
			Handler:    _EdgeDaemonService_ValidatePin_Handler,
		},
		{
			MethodName: "SetPin",
			Handler:    _EdgeDaemonService_SetPin_Handler,
		},
		{
			MethodName: "UnlockDevice",
			Handler:    _EdgeDaemonService_UnlockDevice_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _EdgeDaemonService_GetSettings_Handler,
		},
		{
			MethodName: "UpdateSetting",
			Handler:    _EdgeDaemonService_UpdateSetting_Handler,
		},
		{
			MethodName: "FactoryReset",
			Handler:    _EdgeDaemonService_FactoryReset_Handler,
		},
		{
			MethodName: "ListWiFiNetworks",
			Handler:    _EdgeDaemonService_ListWiFiNetworks_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WatchDeviceStatus",
			Handler:       _EdgeDaemonService_WatchDeviceStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchPrintJobs",
			Handler:       _EdgeDaemonService_WatchPrintJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "WatchPreview",
			Handler:       _EdgeDaemonService_WatchPreview_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "edge_ipc.proto",
}
