import {
  Injectable,
  Logger,
  UnauthorizedException,
  InternalServerErrorException,
} from '@nestjs/common';
import * as client from 'openid-client';
import { ParentAuthService } from './parent-auth.service';

/**
 * OIDC (OpenID Connect) authentication service.
 *
 * Supports Authorization Code Flow + PKCE via any standard OIDC provider.
 * When `OIDC_ISSUER` is not set, `isConfigured()` returns `false` and
 * the app falls back to the dev password login.
 *
 * Env variables:
 *   OIDC_ISSUER          — Provider issuer URL (e.g. https://accounts.google.com)
 *   OIDC_CLIENT_ID       — OAuth 2.0 client ID
 *   OIDC_CLIENT_SECRET   — OAuth 2.0 client secret (optional for PKCE)
 *   OIDC_REDIRECT_URI    — Callback URL (default http://localhost:3002/v1/parent/auth/oidc/callback)
 *   OIDC_SCOPE           — Space-separated scopes (default "openid email profile")
 *   OIDC_WEIXIN_APP_ID   — WeChat OAuth app ID (alternative provider)
 *   OIDC_WEIXIN_SECRET   — WeChat OAuth secret
 *   OIDC_PARAM_HOUSEHOLD_ID — Claim path for household_id (default "household_id")
 */
@Injectable()
export class OidcService {
  private readonly logger = new Logger(OidcService.name);
  private config: client.Configuration | null = null;

  constructor(
    private readonly auth: ParentAuthService,
  ) {
    this.initConfig().catch((err) =>
      this.logger.warn(`OIDC not configured: ${(err as Error).message}`),
    );
  }

  private async initConfig(): Promise<void> {
    const issuerUrl = process.env.OIDC_ISSUER?.trim();
    if (!issuerUrl) return;
    const clientId = process.env.OIDC_CLIENT_ID?.trim();
    if (!clientId) {
      this.logger.warn('OIDC_ISSUER set but OIDC_CLIENT_ID missing');
      return;
    }
    const clientSecret = process.env.OIDC_CLIENT_SECRET?.trim();
    try {
      const serverUrl = new URL(issuerUrl);
      this.config = await client.discovery(serverUrl, clientId, clientSecret);
      this.logger.log(`OIDC: configured for ${issuerUrl}`);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      this.logger.warn(`OIDC: failed to discover issuer ${issuerUrl}: ${msg}`);
    }
  }

  /** Whether OIDC is configured and ready. */
  isConfigured(): boolean {
    return this.config !== null;
  }

  /**
   * Generate PKCE challenge and return the authorization URL + session state.
   *
   * Store `state` and `codeVerifier` in the caller's session (e.g. httpOnly cookies)
   * for verification in `handleCallback()`.
   */
  async getAuthorizationUrl(): Promise<{
    url: string;
    state: string;
    codeVerifier: string;
  }> {
    if (!this.config) {
      throw new InternalServerErrorException({
        code: 'OIDC_NOT_CONFIGURED',
        message: 'OIDC provider is not configured',
      });
    }

    const redirectUri =
      process.env.OIDC_REDIRECT_URI?.trim() ||
      'http://localhost:3002/v1/parent/auth/oidc/callback';
    const scope = process.env.OIDC_SCOPE?.trim() || 'openid email profile';
    const codeVerifier = client.randomPKCECodeVerifier();
    const codeChallenge = await client.calculatePKCECodeChallenge(codeVerifier);
    const state = client.randomState();

    const parameters: Record<string, string> = {
      redirect_uri: redirectUri,
      scope,
      code_challenge: codeChallenge,
      code_challenge_method: 'S256',
      state,
    };

    const url = client.buildAuthorizationUrl(this.config, parameters);
    return { url: url.href, state, codeVerifier };
  }

  /**
   * Handle OIDC callback: exchange authorization code for tokens, issue our
   * own JWT via ParentAuthService.
   *
   * @param callbackUrl - The full callback URL (including query params) as received by the server
   * @param codeVerifier - PKCE code verifier from the initial `getAuthorizationUrl()` call
   * @param expectedState - The `state` value that was generated by `getAuthorizationUrl()`
   */
  async handleCallback(
    callbackUrl: string,
    codeVerifier: string,
    expectedState: string,
  ): Promise<{
    access_token: string;
    refresh_token: string;
    token_type: 'Bearer';
    expires_in: number;
  }> {
    if (!this.config) {
      throw new InternalServerErrorException({
        code: 'OIDC_NOT_CONFIGURED',
        message: 'OIDC provider is not configured',
      });
    }

    let tokens: client.TokenEndpointResponse;
    try {
      tokens = await client.authorizationCodeGrant(
        this.config,
        new URL(callbackUrl),
        {
          pkceCodeVerifier: codeVerifier,
          expectedState,
        },
      );
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      this.logger.warn(`OIDC callback error: ${msg}`);
      throw new UnauthorizedException({
        code: 'OIDC_CALLBACK_FAILED',
        message: 'Failed to exchange authorization code for tokens',
      });
    }

    if (!tokens.access_token) {
      throw new UnauthorizedException({
        code: 'OIDC_NO_ACCESS_TOKEN',
        message: 'No access token in OIDC response',
      });
    }

    // Extract claims from ID token if available
    if (tokens.id_token) {
      const idTokenParts = tokens.id_token.split('.');
      if (idTokenParts.length >= 2) {
        try {
          const payload = JSON.parse(
            Buffer.from(idTokenParts[1], 'base64url').toString('utf8'),
          );
          const sub = payload.sub || 'oidc:unknown';
          const email = (payload.email as string) || `${sub}@oidc.local`;
          const householdId = this.extractHouseholdId(payload);
          return this.auth.issueTokensFromOidc(sub, email, householdId);
        } catch {
          // Fall through to userinfo
        }
      }
    }

    // Fallback: fetch userinfo endpoint
    try {
      const userInfoRes = await client.fetchProtectedResource(
        this.config,
        tokens.access_token,
        new URL(this.config.serverMetadata().userinfo_endpoint!),
        'GET',
      );
      const body = (await userInfoRes.json()) as Record<string, unknown>;
      const sub = String(body.sub || 'oidc:unknown');
      const email = String(body.email || `${sub}@oidc.local`);
      const householdId = this.extractHouseholdId(body);
      return this.auth.issueTokensFromOidc(sub, email, householdId);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      this.logger.warn(`OIDC userinfo failed: ${msg}`);
      throw new UnauthorizedException({
        code: 'OIDC_USERINFO_FAILED',
        message: 'Failed to fetch userinfo after OIDC callback',
      });
    }
  }

  /**
   * Extract household_id from OIDC claims.
   * Configurable via `OIDC_PARAM_HOUSEHOLD_ID` (e.g. "custom.household_id").
   */
  private extractHouseholdId(claims: Record<string, unknown>): string {
    const path =
      process.env.OIDC_PARAM_HOUSEHOLD_ID?.trim() || 'household_id';
    const value = path.split('.').reduce<unknown>((obj, key) => {
      if (obj && typeof obj === 'object') return (obj as Record<string, unknown>)[key];
      return undefined;
    }, claims);
    if (typeof value === 'string' && value) return value;
    return 'household-oidc-default';
  }
}
